### ISSUE TITLE
A text input length limit and warning on the frontend.

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#1]
Users can enter a long text right now, yet these are rejected on later steps. A warning can appear when there are more than 77(?) characters entered.

**Comment by voodoohop** [comment]
It's a 77 token limit which is not exactly translatable to characters. Typically a word is split into two or three tokens....

**Comment by voodoohop** [comment]
We should make a reasonable estimate. I will run some tests. I imagine it would be around 200 characters

**Comment by gokaykucuk** [comment]
@voodoohop as far as understood, now it makes sense to put this into the notebooks themselves as an attribute in notebook params.
