### ISSUE TITLE
Notification after x minutes captcha in colab tab

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#129]
- [ ] measure time to captcha
- [ ] create notification with button or text

**Comment by jacksongoode** [comment]
This potentially could break Googles ToS? I've also had experiences where the runtime will disconnect without a captcha.

**Comment by voodoohop** [comment]
Good point. We should definitely read Colab's terms at some point. ;)

**Comment by voodoohop** [comment]
I noticed that you get like 20 minutes of GPU even after the captcha appears. Most people only generate one or two things on the site which takes less time and then it's actually good that Google shuts off the GPU. Thinking of the carbon cost.
