### ISSUE TITLE
Display MIT/relevant license for the notebooks

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#147]

**Comment by voodoohop** [comment]
yeah i think it could just be a small thing with a little logo of the license type
and with a mouseover you see details of the license
so in the case of stylegan3
it doesnt allow commercial use

**Comment by gokaykucuk** [comment]
We can use the metadata in the notebook's for LICENSE information. This information can be fetched and displayed by pollinations.ai.

**Comment by voodoohop** [comment]
I vote for using the markdown of the actual notebooks now and moving a ui for this to milestone 0.3
