### ISSUE TITLE
Create accounts for external services

### ISSUE THREAD

**Issue by gokaykucuk** [pollinations/pollinations#15]

**Comment by gokaykucuk** [comment]
E-mail : Protonmail or a aliasing service
Patreon
Hetzner

**Comment by voodoohop** [comment]
Mail forwarder / aliaser
https://improvmx.com/

But in the end we will need a shared account which we receive the inbox so we might as well create a protonmail

**Comment by voodoohop** [comment]
Created a substack account:
https://pollination.substack.com/

We can try and use that as our CMS for  writing blog-type articles and import the content via RSS or something

@gokaykucuk do you think I should do `pollinations_ai` instead of `pollination`? `pollinations` was already in use

**Comment by gokaykucuk** [comment]
@voodoohop imo pollinations_ai looks better

**Comment by gokaykucuk** [comment]
@gokaykucuk mail forwarder also looks cool, but I would also vote for creating a protonmail just to create less notifications in our lives.

**Comment by voodoohop** [comment]
https://www.linkedin.com/company/pollinations-ai

**Comment by voodoohop** [comment]
left: create patreon account
