### ISSUE TITLE
Move out the built files in /dist folder to CI

### ISSUE THREAD

**Issue by gokaykucuk** [pollinations/pollinations#159]
- [ ]  Remove the /dist folder from the repository.
- [ ] Add building of /dist folder to CI build steps.
- [ ] Make the pollinator get built files from CDN instead of github.
- [ ] Remove the dist/ folder and check the repo size.

The theory is, removal of these folders might make the repository smaller. Report back if this is the case by using https://github.com/rtyley/bfg-repo-cleaner and checking the repo size afterwards.

**Comment by voodoohop** [comment]
Need to update this action to use CDN: https://github.com/pollinations/hive/blob/main/.github/workflows/publish_ipfs.yml

Can't we use the github "releases" as the CDN? Or even IPFS better...
