### ISSUE TITLE
Add "debounce" or smt similar to frontend updates otherwise the frontend locks up when updates/sec is too hig

### ISSUE THREAD

**Issue by gokaykucuk** [pollinations/pollinations#16]
Try this one again, to see if removing the colab ipfs node had any effect on the issue.

**Comment by voodoohop** [comment]
Do you know if the hashes are received on the client and all we'd need to do is debounce+throttle on the client side? or should we already throttle the state updates coming from the server.

**Comment by voodoohop** [comment]
server=colab client=polllinations.ai

**Comment by gokaykucuk** [comment]
@voodoohop I think we don't need to stop the state updates coming from the server. It feels like the updates are causing a full re-render of the page and that's creating the bottleneck. So if we don't update the UI even if there are updates queued and just update the client once after a certain debounce/throttle point it should be fine.

**Comment by voodoohop** [comment]
Closing this as I haven't seen it happen in a while + We are using only one IPFS node so updates should be pretty instantaneous. Can revisit later.
