### ISSUE TITLE
Telegram bot as UI

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#2]

**Comment by voodoohop** [comment]
We'd just require a GPU. If we have access to free GPU-hours I guess we could make a twitter/facebook/telegram/... bot

**Comment by voodoohop** [comment]
We are using Ayrshare to automate social posting which at least allows to post to telegram automatically.

**Comment by gokaykucuk** [comment]
> We are using Ayrshare to automate social posting which at least allows to post to telegram automatically.

So we can also create a telegram channel for it to post all the updates. Maybe we can postpone the inputs from telegram for now until we have the free GPU hours.

**Comment by voodoohop** [comment]
https://github.com/pollinations/pollinations/blob/master/app/src/backend/functions/social-post.js

**Comment by voodoohop** [comment]
528b5a786ada23148809067ae8fdf1fe30d9202b
