### ISSUE TITLE
Switch between different painters during christmas every 3 posts

### ISSUE THREAD

**Issue by gokaykucuk** [pollinations/pollinations#209]
To create a visual effect on our Instagram page, we can switch between different painters on every 3rd post. Because Instagram has 3 posts in every row, this change will be visible on our Instagram page as a nice visual effect.

 - Do we need to create an external counter? or can we think of a nice way of implementing this with IPFS so we can maybe keep being decentralized. One idea might be having an external microservice(like `social-post`) to be used as a state and using IPFS pubsub from pollinators or `social-post` as a way of updating this state. Building this feature directly in `social-post` looks also a good way of doing it, because this is under the responsibility of `social-post`.
 - Should we also keep this feature in some form for the future?

**Comment by eni-lorac** [comment]
by the way: it will only look synchronized and create the effect 1/3 of the times

**Comment by voodoohop** [comment]
We'd need to build in logic into each notebook to poll the post count. I'm not sure the effect we achieve will justify the engineering effort. 

Especially since only the CLIP+VQGAN really takes style into account convincingly and over 50% of image posts these days are by different models. Also it only applies to one of the many social networks we post on. (although probably the one with far more interactions)

**Comment by voodoohop** [comment]
Of course, I love these ideas, so if you see a nice way to implement this especially if it could be used for something in the future please go ahead. 

I'd just intuitively avoid adding logic that deals with state and post counts etc if it's only applicable to instagram and this christmas action.

I think randomizing the style suffix or doing for example daily changes can also be a nice effect.

**Comment by gokaykucuk** [comment]
Nope, thinking again, I agree that it might be unnecessary complexity for now. So let's skip this one.

**Comment by voodoohop** [comment]
Buuut this brings us to an interesting point which is that at some point we cant avoid having a mutable database kind of thing ideally hosted on ipfs+ipns or using one of the db abstractions built on top of ipfs

**Comment by gokaykucuk** [comment]
Yeah, true. Maybe it's a nice opportunity to test out `https://github.com/orbitdb/orbit-db`. Yet their repo seems a bit silent compared to IPFS.

**Comment by gokaykucuk** [comment]
Ah, I think it's not an option because `Compatible with js-ipfs versions <= 0.52 and go-ipfs versions <= 0.6.0`.

**Comment by gokaykucuk** [comment]
@voodoohop I also found this one, it's the system that orbit-db uses underneath, https://github.com/orbitdb/ipfs-log. This project seems like it should be enough for our use case. I'll try to see if it works.
