### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by gokaykucuk** [pollinations/pollinations#24]
-> Store a history of created pollinations in browser localStorage to show.

**Comment by voodoohop** [comment]
The Gallery could also be populated dynamically using our social post history. Either through ayrshare's api or directly with the social media apis.

Ideally we have two sections. One with popular notebooks of other people and one with the history of your own pollinations (which would come from localStorage)

**Comment by gokaykucuk** [comment]
We need a reddit style algorithm, a ranking that combines the date of publishing + reaction from posts and orders the gallery feed.
