### ISSUE TITLE
Do a hosted GPU test for Google Cloud.

### ISSUE THREAD

**Issue by gokaykucuk** [pollinations/pollinations#247]
Also before starting off, we should shoot an e-mail to google and ask for credits

**Comment by voodoohop** [comment]
I tested it already through colab. When you sign up to GCP you get 300 dollars in credits anyway

**Comment by gokaykucuk** [comment]
I've charted whats on my mind as interfaces etc.

![pollinations_gpu_flow drawio](https://user-images.githubusercontent.com/378888/160272649-ce7ed499-3734-414e-8613-c491561b62a9.png)
