### ISSUE TITLE
Create an indexer for Pollen

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#263]

**Comment by gokaykucuk** [comment]
So with the deployment of pollinations-backend to supabase, we can think of merging ipfs-indexer we have(https://github.com/pollinations/ipfs-indexer) into our backend(https://github.com/pollinations/ipfs-indexer) and use it for both purposes.

IPFS Indexer works with 2 main strategies,
- Get a batch of CID's
- Listen to a pubsub channel (namely "done_pollen" for us).

After receiving a CID from either channel,
- Indexer will download the CID
- Check the contents of the CID
- Index the CID whether it errored out or "done"
