### ISSUE TITLE
Save pollens to supabase  for logged-in users

### ISSUE THREAD

**Issue by gokaykucuk** [pollinations/pollinations#267]
We would like to save pollens a user created under its own account, so users can go back and browse their pollens in the future.

**Comment by gokaykucuk** [comment]
@voodoohop shall we continue with the 1 CID idea or shall we save them individually so they are "categorised" and "searchable"?

**Comment by gokaykucuk** [comment]
After discussing the options, while local pollens are saved with a single CID works good for just storage and infinite scroll, we've figured out saving every pollen as a different entity has the following advantages,
- Search
- Categories by output
- Categories by model
- Tagging
- Favorites

And any other feature that we might come up with in the future can be implemented as long as we are saving all pollens as different entities in supabase instead of a single CID.

**Comment by voodoohop** [comment]
Closing for now as we are still evaluating the best UX flow
