### ISSUE TITLE
Create a cron job to enter the public-ipfs docker container and run ipfs repo gc

### ISSUE THREAD

**Issue by gokaykucuk** [pollinations/pollinations#273]

**Comment by voodoohop** [comment]
@gokaykucuk  have you tried the --enable-gc for runtime gc? maybe it was just failing on our other node because it was so much data and a slow hd

**Comment by gokaykucuk** [comment]
@voodoohop i think we can merge it with writing our own dockerfile than. Makes sense, I'll take this as the next item.
