### ISSUE TITLE
When the user  does not have access to a GPU on Colab, render a nice message explaining the problem

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#276]

**Comment by voodoohop** [comment]
<img width="399" alt="Screenshot 2022-03-29 at 12 45 45" src="https://user-images.githubusercontent.com/5099901/160608759-eeb2ecc8-0f2f-436d-b694-f3413e8f2fde.png">
<img width="505" alt="Screenshot 2022-03-29 at 12 44 30" src="https://user-images.githubusercontent.com/5099901/160608766-e265a2c9-16e7-47c1-9e70-a6c4cdeefa7d.png">

**Comment by voodoohop** [comment]
Currently this error is shown:
<img width="1024" alt="Screenshot 2022-03-29 at 14 16 20" src="https://user-images.githubusercontent.com/5099901/160609174-6b29f6aa-dadb-42ce-96c8-14d47f6d8765.png">

**Comment by nielsrolf** [comment]
Blocked by: review by UX team
