### ISSUE TITLE
Deploy IPFS to Hetzner/Scaleaway/Digitalocean

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#29]

**Comment by gokaykucuk** [comment]
So this doesn't go along well with our idea of "decentralization". Any AWS service we use will create a "vendor lock in", so at this point we will limit ourselves using only Docker etc and running everything we have on bare bone virtual machines. With this constraint AWS doesn't make sense, so we will create an account on hetzner/scaleaway which provides similar systems with half the price for IPFS hosting.

**Comment by gokaykucuk** [comment]
We need a script to gather all the posted pollinations content URLs, which we can get from aryshare API

**Comment by gokaykucuk** [comment]
- Make docker-compose work.
