### ISSUE TITLE
Simplify Pollinations <-> IPFS <-> Colab communication

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#3]
Implement unidirectional data-flow.

All state is still stored in IPFS. 

Colab notebook will be only allowed to write to /output and read from /input.

Pollinations will be only allowed to write to /input and read from /output

**Comment by gokaykucuk** [comment]
@voodoohop I think we can be more explicit with the folder names like /collab-to-pollinations and /pollinations-to-collab. It can make it easier to discuss in the future.
