### ISSUE TITLE
Social Media Posting

### ISSUE THREAD

**Issue by gokaykucuk** [pollinations/pollinations#30]
- [x] figure out how to specify a thumbnail image for the video (easiest is to copy the final frame to the first frame maybe)
- [x] Resize video in ffmpeg to be portable on Instagram and twitter
- [x] Show links to posted content when done
- [x] add checkbox to disable posting
- [x] Meta tags SSR not working properly.  from #34 
- [x] move call of netlify function to frontend. separate per social network
- [x] make social media posting optional (add checkbox)
- [x] Only apply maturity filter to whole words
- [x] Change maturity filter to *** words instead of filtering the posts
- [x] Maturity filter
- [x] Shorten title for twitter #51 
- [x] Show social media icons in menu for people to find the feeds even without creating anything
the thumbnail is a bit annoying if its the first frame since these  models start from noise
- [x]  Separate serverless function that fetches IPFS state from function that does post. Use redirect

**Comment by voodoohop** [comment]
- [ ] figure out how to specify a thumbnail image for the video
- [ ] Resize video in ffmpeg to be portable on Instagram and twitter

the thumbnail is a bit annoying if its the first frame since these  models start from noise

**Comment by voodoohop** [comment]
https://user-images.githubusercontent.com/378888/127774709-9125d5c4-3415-4a2d-a40a-f0d87d720b2c.mov

When navigated with a googlebot user agent, netlify doesn't render the site properly

**Comment by voodoohop** [comment]
55dfba1f6c50bc133d0d68d864007ff4969ae6b7
