### ISSUE TITLE
Meta tags SSR not working properly.

### ISSUE THREAD

**Issue by gokaykucuk** [pollinations/pollinations#34]
https://user-images.githubusercontent.com/378888/127774709-9125d5c4-3415-4a2d-a40a-f0d87d720b2c.mov

When navigated with a googlebot user agent, netlify doesn't render the site properly

**Comment by voodoohop** [comment]
merged to #30

**Comment by voodoohop** [comment]
55dfba1f6c50bc133d0d68d864007ff4969ae6b7
