### ISSUE TITLE
UI cleanup

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#35]
- [x] Move node and content id into nav  bar
- [x] Show help button more 0656da6fad43eca6c7775940ef6aa651bb63cbb6
- [x] Help modal is not scrollable depending on screen size
<img width="988" alt="Screenshot 2021-08-01 at 16 40 20" src="https://user-images.githubusercontent.com/5099901/127774961-db2698fa-8f9d-40bd-be2e-0e3662fe6fc8.png">

**Comment by gokaykucuk** [comment]
taking a note, "Help modal is not scrollable depending on screen size" only occurs on my mobile phone, but if i make the screen smaller on my pc, it works. So from my side it can't be tested on desktop browser.
