### ISSUE TITLE
Rename the input labels

### ISSUE THREAD

**Issue by gokaykucuk** [pollinations/pollinations#37]

**Comment by voodoohop** [comment]
Decided to use comments before the parameter definition like this:
![Screenshot 2021-08-11 at 00 26 34](https://user-images.githubusercontent.com/5099901/129094892-d37e96b0-e562-47e3-a98d-485be7329a72.jpeg)

requires creating a parser

**Comment by gokaykucuk** [comment]
@voodoohop I couldn't find the comments before params on this -> https://pollinations.ai/ipfs/QmNheqL4CeFrZa4oBZHaXRpHx4Lc6bTpLx8X2txK1LLkGB?filename=notebook.ipynb. How can I update the notebooks, let's document this as one of the next tasks.

**Comment by voodoohop** [comment]
@gokaykucuk to update the notebooks at the moment you can download the notebook from ipfs change it, do ipfs add and then change the hash in polllinations to point to the new notebook

**Comment by voodoohop** [comment]
https://github.com/pollinations/pollinations/pull/92
