### ISSUE TITLE
Connection to IPFS - Text Field Remains Inaccessible.

### ISSUE THREAD

**Issue by My-Inq** [pollinations/pollinations#44]
Waiting for form submission
  pollinate CLI options {
  path: '/content/ipfs/input',
  receive: true,
  send: false,
  once: true,
  ipns: true,
  nodeid: 'qbqSticyhxxxx',
  debounce: 500,
  execute: null,
  logout: null
} +0ms
  ipfsConnector localhost:5001 is not reachable. Connecting to https://ipfs.pollinations.ai +0ms
  ipfsConnector NodeID qbqSticyhxxxx +53ms
  ipfsConnector Subscribing to pubsub events from qbqSticyhxxxx/input +0ms
  ipfsConnector Subscribing to pubsub events from qbqSticyhxxxx/input +1ms
  ipfsConnector Executing subscribe qbqSticyhxxxx/input +0ms

**Comment by voodoohop** [comment]
Hey! I will look into this. We perceived it sometimes loses connection after a while but it's usually possible to restore by clicking "Runtime -> Restart and Run All" in _Colab_ and on _Pollinations_ clicking one of the notebooks in the menu at the top.

Could you send screenshots of both the _pollinations_ and the _colab_ tab? Are you using Chrome? We have only really tested it on Google Chrome so far.

**Comment by voodoohop** [comment]
Closed due to inactivity
