### ISSUE TITLE
Advanced mode for more settings for experienced users

### ISSUE THREAD

**Issue by jacksongoode** [pollinations/pollinations#53]
In the current iteration, the interaction the user has with the params of the model are quite limited. It would make sense for more experienced users to have some ability to change additional params with an "Advanced mode" toggle that would reveal other settings that were hidden (temperature, iteration count, save count, and others).

**Comment by voodoohop** [comment]
This one is quite easy to do. We wanted to add some more notebooks to the notebook list anyway. So we will add some expert ones that just expose most of the parameters.

**Comment by gokaykucuk** [comment]
I think this one we can merge with -> https://github.com/pollinations/pollinations/pull/48 . There the target was to simplify the notebooks, but we concluded that we need a switch to expert mode. All the parameters other than the main parameter can go into "expert mode" params.

**Comment by voodoohop** [comment]
agree. i will just close this one in favor of #48
