### ISSUE TITLE
Document Notebook Upload Procedure

### ISSUE THREAD

**Issue by gokaykucuk** [pollinations/pollinations#59]
- How do we update the notebooks?
- Should we automate deployment of the notebooks from this repository with a simple CI?

**Comment by voodoohop** [comment]
Great idea about the CI. I was thinking about having a page one can drop a notebook onto in the future. But let's start with your suggestion.

**Comment by voodoohop** [comment]
Added CI. For uploading custom notebooks its still a bit manual (need to wrap in folder /input/notebook.ipynb) but it's documented in the readme now
