### ISSUE TITLE
Make list of projects integrating Pollinations

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#634]
- anyai by @meow_18838 (shall we link a page for it or would it be too much users)?
- discord bot by @zngzy https://discord.com/oauth2/authorize?client_id=1123551005993357342
- SillyTavern https://docs.sillytavern.app/extensions/stable-diffusion/
- Python package https://pypi.org/project/pollinations/
- Karma.yt by @dg https://karma.yt
- Telegram bot by Wong Wei Hao http://t.me/pollinationsbot
- Whatsapp Group by @dg https://chat.whatsapp.com/KI37JqT5aYdL9WBYMyyjDV
- Pollinator https://github.com/g-aggarwal/Pollinator
Open-source Android App for Text to Image generation, using Pollinations AI's endpoint.
- Websim by @thomash https://websim.ai/c/bXsmNE96e3op5rtUS

**Comment by ThomasH** [comment]
Hi,I think you linked the wrong ThomasH, I don't have a GitHub project you mentioned.BRThomas
-------- Ursprüngliche Nachricht --------Von: voodoohop ***@***.***> Datum: 17.09.24  01:01  (GMT+01:00) An: pollinations/pollinations ***@***.***> Cc: ThomasH ***@***.***>, Mention ***@***.***> Betreff: Re: [pollinations/pollinations] Make list of projects integrating
  Pollinations (Issue #634) 
Closed #634 as completed.
