### ISSUE TITLE
Potential for adding a 'system' role to usePollinationsText

### ISSUE THREAD

**Issue by diogo-karma** [pollinations/pollinations#664]
I know it works well through `usePollinationsChat`, and `usePollinationsText` is designed to be simple, which I appreciate. However, what are your thoughts on adding support for sending a role="system" as well?"

`const text = usePollinationsText('Write a short haiku about Pollinations.AI', 'You are a Hindu poet');`

**Comment by voodoohop** [comment]
yes i was considering it. with usePollinationsChat it's already possible I think.

we can just call the endpoint with a post request and send the system prompt along as the first message with role system

**Comment by voodoohop** [comment]
@diogo-karma if you want you can review the pull request: https://github.com/pollinations/pollinations/pull/667
