### ISSUE TITLE
Today python pollination is not working

### ISSUE THREAD

**Issue by masbenny** [pollinations/pollinations#684]
**URL Result Link Dead:** [HERE](https://image.pollinations.ai/prompt/%20Jade%20Dynasty,%20luxueqi,%20girl,%20jewelry,%20hair%20ornament,%20crystal%20earrings,%20earrings,%20grey%20eyes,%20long%20hair,%20black%20hair,%20forehead%20mark,%20upper%20body,%20crystal,%20crystal%20hair%20ornament,%20alpha%20transparency,%20see-through,%20hair%20bun,%20dress,%20white%20dress,%20natural%20skin,%20realistic,?model=turbo&width=1080&height=1920&seed=1001&nologo=true)

 
**504 ERROR**
![Screenshot 2024-09-17 171741](https://github.com/user-attachments/assets/887bbb30-8553-4ef4-93e5-f5118e97297b)

 **Bring back pollinations.ai 1.0.1 please...**

**Comment by voodoohop** [comment]
Hi! It may have been a temporary issue. Your link seems to be working now. Could you let me know if it occurs frequently?

You could also consider using the flux model instead of turbo as the quality is higher and we have a few more servers allocated to it.

**Comment by masbenny** [comment]
> Hi! It may have been a temporary issue. Your link seems to be working now. Could you let me know if it occurs frequently?
> 
> You could also consider using the flux model instead of turbo as the quality is higher and we have a few more servers allocated to it.

The problem is solved now, maybe there was a problem since pollination updated the website theme this day to be more attractive. And From what I know, the pollination server often has errors, usually only a few minutes and a maximum of 1 hour. It can be seen when the website cannot request an image feed.
