### ISSUE TITLE
Deal with 8gb RAM GPU's

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#76]
Possible solutions:
- Show user a subset of notebooks that run with less RAM
- Notebooks degrade their quality and adapt to lower RAM
- User gets a message to try again later
...

**Comment by gokaykucuk** [comment]
- Verify if VQGAN + Clip works on 8GB or not.
  - If not, then we should tell the user that they can try again later or premium subscription on collab doesn't have this issue.

**Comment by voodoohop** [comment]
VQGAN+Clip notebook seems to work fine with the small GPUs. Will try and tweak the other notebooks to run on 8GB too
