### ISSUE TITLE
State Management Discussion

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#8]
im in a bit of a decision with the state management...

at the moment we have one "global" shared state in the form of an ipfs hash
the state can be seen as a json object or a folder structure
on the colab side the IPFS state is persisted directly to and from the file system
the colab writes to /output pollinations writes to /input
and whenever either has changed the global state it sends a new hash on a pubsub channel
but its not so clean because both can change either /input or /output its not completely unidirectional data flow
so im thinking the colab notebook should only send its output content id and pollinations should only send the input content id
but then i loose the niceness of having one hash
that describes the whole run including inputs and outputs

**Comment by voodoohop** [comment]
So this hash is overriden by two different clients
Then first of all, I was thinking if keeping the same <id> after i click reset/cancel makes sense or not

if we made it more unidirectional it wouldnt have these failure stages. i.e. colab cannot change /input and pollinations cannot change /output but only read from it vice versa
theres a finite state machine in there somehow
yeah each small thing you do the theory was it goes into the global state. so if pollinations wants to cancel the current proces colab is doing it merges a {input: {requestCancel:true}} to the global state
and then i had made colab remove the requestCancel once it had actually cancelled the run18m
but that meant both were writing to the same object
and it got a bit messy
Yep I think this is the problem
I think they should not write to same state

**Comment by voodoohop** [comment]
then i thought we have a satte of colab and a state of pollinations which both represent kindof the inputs and the outputs to a computation
and we could just join them inn the frontend
to one hash
which is in the url you share etc

**Comment by voodoohop** [comment]
you want to add a word to the prompt
11m
then you want to cancel it
11m
change the prompt a bit
11m
and restart
11m

You
you want to add a word to the prompt
This won't happen that much
10m
Either i can still reset it
10m
Or more than that, i never know really what deepdaze is gonna come up with
9m
So i want to see this result first
9m
And run it again with the word
9m

gokay
And run it again with the word
After adding the word i tried to mean
8m
ok i will finish my new state implementation in the most simple way without a cancel/stop functionality
8m
and then we see if it is easy to fit in
8m

❤️
i agree that its best to keep things simple and stable at first
8m
because its there now
7m
but its not even really usable
7m
and just complicates things

**Comment by gokaykucuk** [comment]
I think issue https://github.com/pollinations/pollinations/issues/10 is also related where pollinations.ai stopped showing any input element.
