### ISSUE TITLE
Is the watermark mandatory?

### ISSUE THREAD

**Issue by Kamoba** [pollinations/pollinations#815]
Hey guys!

Fist of all thanks for this, I love it.

The test in the browser works without a watermark but when retrieving using a JS script, I got a watermark on the image.
Is this part of the term of service or what? I didn't see any mention of this.

![Pollinations ](https://github.com/user-attachments/assets/d85ef12d-59b1-41bd-9aae-9f0ea511fc5b)

**Comment by voodoohop** [comment]
If you add the `nologo=true` parameter to the url you can remove the watermak. This only works for flux and turbo models as the others are hosted on third-party infrastructure.

**Comment by Kamoba** [comment]
I notice even from the browser we got time to time the watermark.
I tried this:
```
https://image.pollinations.ai/prompt/conceptual_isometric_world_of_pollinations_ai_surreal_hyperrealistic_digital_garden&model=flux&nologo=true
```
Still got watermark.

**Comment by flowa-ai** [comment]
After a prompt, start parameters with a ? and separate them by &

?model=flux&nologo=true

https://image.pollinations.ai/prompt/conceptual_isometric_world_of_pollinations_ai_surreal_hyperrealistic_digital_garden?model=flux&nologo=true
