### ISSUE TITLE
Correct attribution for unity model

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#868]
i dont mean to be a bug a boo
but...
can You change the by GFourteen on the Unity model?
to:
Unity AI Lab
There are  a number of us in the Unity AI Lab that work on the Unity prompts
so just seems off that it sayd "by @GFourteen"
@thomash
im just the guy that writes the 3 cent check a day for the web domain:
https://blog.unityailab.com/unity.html

**Comment by ThomasH** [comment]
Sry, but you mentioned the wrong ThomasH. I have nothing to do with Unity or Unity AI
