### ISSUE TITLE
Discover if we can somehow "cache" all of a notebooks dependencies on IPFS and improve a notebooks startup time by just loading this "virtual environment"

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#9]

**Comment by voodoohop** [comment]
ideally without having to modify the notebook too much. I'd still like to make it as easy as possible to "import" existing colab notebooks. But maybe its not sooo necessary.

**Comment by voodoohop** [comment]
There has been an interesting development with the NIX package manager which I love but have never used integrating IPFS

**Comment by gokaykucuk** [comment]
We should also try to "lock" the dependencies of our notebooks. We can prepare a minor version locked requirements.txt file.

**Comment by gokaykucuk** [comment]
"Nix" should be also under the radar.
