### ISSUE TITLE
[Loading] Loading State issue using usePollinationsImage

### ISSUE THREAD

**Issue by leohonlmc** [pollinations/pollinations#903]
Using imageURL doesn't fully capture the loading state while generating images. Switching to Axios to call `https://image.pollinations.ai/prompt/${inputPrompt}` might resolve the issue.

**Comment by voodoohop** [comment]
Sorry about the delay in responding.

Can't you determine the loading state based on whether the returned url changed? at the start it will be null and then it should only change once loading is complete.

We could add an explicit loading boolean though if my suggestion doesn't work or is too complicated.

**Comment by leohonlmc** [comment]
I understand what you're saying, but the imageURL cannot provide a status code like 200. For instance, I added a loading animation during the image generation process. When using imageURL, it only detects the state change from null to my prompt (within 1 second), but it doesn't account for the actual generation time. Hope that make sense.

**Comment by voodoohop** [comment]
Oh sorry. I totally forgot that we changed the `usePollinationsImage` function to not actually fetch the image. 

The idea is that the user most of the time just provides the returned url to the `src` parameter of an `img` tag. You can then use the img's onload function to get the loading state.

Or why don't you just fetch it yourself with axios once you got the url?

**Comment by leohonlmc** [comment]
Yeah, that's the solution I got using Axios, but it seems the params or props are not the same as the package you provide, for example, hiding/showing the brand name. Just food for thought 👍🏻
