### ISSUE TITLE
api overloaded

### ISSUE THREAD

**Issue by Kamal-thakur-py** [pollinations/pollinations#909]
Failed to generate image. Status code: 504
Response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>504 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 9KuQpKlGQZKXGa130JT87kF4fHLmW78kB20ilVEppgdq8ZG5TnWG_Q==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

**Comment by voodoohop** [comment]
should be resolved. please open the issue again if it happens again
