### ISSUE TITLE
Add an edit in colab link

### ISSUE THREAD

**Issue by voodoohop** [pollinations/pollinations#99]
we want to encourage people to also get into hacking the models

**Comment by gokaykucuk** [comment]
@voodoohop what does this link supposed to do? Directly the notebook(not pollinator) in collab?

**Comment by voodoohop** [comment]
Yes. E.g. https://colab.research.google.com/github/pollinations/hive/blob/main/notebooks/Text-To-Image/2%20CLIP-Guided%20Diffusion.ipynb

maybe it it's one of the things that appears when you click the "advanced" button or whatever way you get to "expert" mode
